[package]
name = "mena-rust"
version = "1.0.0"
edition = "2021"

[profile.release]
strip = true
#codegen-units = 1
#lto = true
debug = false

[dependencies]
thirtyfour = "0.31.0"
tokio = "1.20.1"
job_scheduler_ng = "2.0.1"
teloxide = "0.10.1"
image = "0.24.3" 
serde = "1.0.144"
toml = "0.5.9"
