version: '3.9'
services:
  pterodactyl:
    image: mena:pterodactyl
    build:
      context: .
      dockerfile: ./docker/pterodactyl/Dockerfile
  native:
    image: mena:native
    build: 
      context: .
      dockerfile: ./docker/native/Dockerfile